### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by dharrigan** [fishi0x01/vsh#10]
Hi,

Interesting project, got a panic:

```
% vsh         
http://vault:8200 /> cd 
panic: runtime error: index out of range

goroutine 1 [running]:
main.executor(0xc00001e216, 0x3)
	/home/fishi/Workspaces/fishi0x01/vsh/main.go:65 +0x6c5
github.com/c-bata/go-prompt.(*Prompt).Run(0xc0001ac400)
	/home/fishi/Workspaces/fishi0x01/vsh/vendor/github.com/c-bata/go-prompt/prompt.go:85 +0x7f2
main.main()
	/home/fishi/Workspaces/fishi0x01/vsh/main.go:144 +0x51a
```

I did this by simply running up vsh, selecting cd and pressing return without choosing the suggestion.

In fact, it seems to happen with all suggestions, without choosing the suggestion, i.e., cp, rm etc...

**Comment by fishi0x01** [comment]
Yes you are absolutely right. Some sanity checks are still missing. Will add them later today :+1:

**Comment by fishi0x01-gc** [comment]
Merged a fix which includes some trivial sanity checking. However, more checks will be added in the (near) future / error handling will be improved. 

I am considering this issue done for now.

**Comment by fishi0x01** [comment]
Merged a fix with some basic sanity checking which should prevent panics like above. 
However, more sanity checks / better error handling will be added in the (near) future.

**Comment by dharrigan** [comment]
Fantastic. Will test.
