### ISSUE TITLE
Support ctrl+p for "Previous command" navigation

### ISSUE THREAD

**Issue by Dispader** [fishi0x01/vsh#103]
crtl-p (and ctrl-n) for previous (next) command navigation is widely supported in shell environments.  It feels like we would enhance user experience by supporting these navigation keys.

**Comment by fishi0x01** [comment]
ctrl-p and ctrl-n keybindings are already supported. I just confirmed locally with the latest vsh release.

vsh uses [c-bata/go-prompt](https://github.com/c-bata/go-prompt) for prompt emulation. It specifically supports ctrl-p and ctrl-n https://github.com/c-bata/go-prompt#keyboard-shortcuts
