### ISSUE TITLE
Support for Vault Token Helpers

### ISSUE THREAD

**Issue by yermulnik** [fishi0x01/vsh#20]
Would be great this super cool tool could leverage https://www.vaultproject.io/docs/commands/token-helper/

**Comment by fishi0x01** [comment]
Thank you for the nice idea :+1: 

I will try to work on that in the coming days.

**Comment by yermulnik** [comment]
Appreciate it. Thanks.

**Comment by fishi0x01** [comment]
I have created a [new release](https://github.com/fishi0x01/vsh/releases/tag/0.4.0) which leverages Vault's token helper mechanism. It works for me and the integration test also looks promising. 

Does that fully solve your feature proposal?

**Comment by yermulnik** [comment]
@fishi0x01 Worked like a charm. Thank you!

**Comment by yermulnik** [comment]
By the way is there a way to turn off auto-completion completely? It drastically slows down `vsh` on a big number of items to be completed on a remote Vault clusters.

**Comment by fishi0x01** [comment]
Very good point :+1: 
Currently `vsh` does not support toggling auto-completion. 
I opened and linked a new issue. Will try to work on that in the coming days.

**Comment by yermulnik** [comment]
Thanks a bunch! =)

**Comment by fishi0x01** [comment]
@yermulnik fyi: 
added a new [release](https://github.com/fishi0x01/vsh/releases/tag/0.4.1) which does some caching to reduce overall query load. That _should_ improve performance a little.

**Comment by yermulnik** [comment]
@fishi0x01 Thanks a lot. Appreciate your work and effort.
