### ISSUE TITLE
Option to toggle auto-completion in interactive mode

### ISSUE THREAD

**Issue by fishi0x01** [fishi0x01/vsh#22]
`vsh` does a lot of queries against vault to do auto-completion. This might lead to low client performance, especially when directories with a lot of items are queried. 

**Requirements:**
- by default, auto-completion should be enabled
- `vsh` should support an option to toggle auto-completion in interactive mode
- a cli start flag should be added to disable auto-completion when starting.

This was first mentioned on https://github.com/fishi0x01/vsh/issues/20

**Comment by fishi0x01** [comment]
Performance _should_ be better now with caching https://github.com/fishi0x01/vsh/issues/23

**Comment by wandergeek** [comment]
+1 here

**Comment by fishi0x01** [comment]
New [release](https://github.com/fishi0x01/vsh/releases/tag/v0.7.0) contains option for toggling path auto-completion on/off
