### ISSUE TITLE
Provide Installation Instructions

### ISSUE THREAD

**Issue by oliverisaac** [fishi0x01/vsh#57]
It'd be handy to provide copy-paste instructions for installing. Bonus points for a `brew` install method :)

**Comment by fishi0x01** [comment]
Truth be told I'm not a mac user - so I'm not very firm with brew :sweat_smile: 
That being said I tried to get a formula done and opened a [PR](https://github.com/Homebrew/homebrew-core/pull/69179) at brew core - lets see if it's valid and gets acked :crossed_fingers: 

Apart from that, nix package and static binary install methods are added to documentation.

**Comment by fishi0x01** [comment]
@oliverisaac `vsh` can now be installed via brew. Installation instructions are merged. Considering this issue done.
