### ISSUE TITLE
Feature request: sed

### ISSUE THREAD

**Issue by mattlqx** [fishi0x01/vsh#59]
First off, nice tool! I was specifically looking for an easy way to search a Vault and grep fits the bill nicely. It would be nice to have a way to change strings recursively in Vault as well ala an in-place "`sed`". Flags could be used to apply only for keys, values or both. It'd make configuration changes very easy across multiple paths (which in our usage maps to different services).

Supporting regex on it (and grep for that matter) would be a big bonus.

**Comment by fishi0x01** [comment]
I like the idea :+1:

Not sure yet when I will have time to work on it, but it is definitely on the backlog.

**Comment by mattlqx** [comment]
Ah, I took your comment to mean "not very soon" so I started down this road. I'll put up my pull for adding regexp and quotes and you can see if you like it.

**Comment by fishi0x01** [comment]
Closing this now, as #69 is merged. Thanks again @mattlqx :bow:
