### ISSUE TITLE
compiling on debian

### ISSUE THREAD

**Issue by linuxnoob121** [fishi0x01/vsh#77]
hi there,

I am just wondering how to compile this on Debian 10. 

Thanks!

**Comment by fishi0x01** [comment]
Hi :wave: 

This is a standard go project, so as long as you have go installed, `go build` will compile it for you. 
Further, there is a make command which also does the job with some extras `make compile`.

**Comment by fishi0x01** [comment]
@linuxnoob121 concerning your compilation issue: 
Which version of go are you using to compile? You can see the version when you run `go version`.
